
- hosts: servers
  vars_files:
    - vars.yml
  gather_facts: false
  become: yes

  tasks:
    - name: Install system packages
      apt: 
        pkg: "{{ item }}"
        update-cache: yes
      with_items: "{{ system_packages }}"

    - name: Create directory for app
      file: >
        path={{ install_root }}/{{ project_name }}
        state=directory

    - name: Make sure postgresql server is running
      service: name=postgresql state=started

    - name: Create database
      postgresql_db: name={{ db_name }}
      become_user: postgres

    - name: Create database user
      postgresql_user: 
        db: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: ALL
      become_user: postgres

    - name: Remove default nginx site
      file: >
        path=/etc/nginx/sites-enabled/default 
        state=absent

- import_playbook: deploy.yml

# vim:ft=ansible:
