---

# A unix path-friendly name
project_name: django_hello

# The base path to install to. You should not need to change this.
install_root: /srv

# The python module path to your project's wsgi file.
wsgi_module: hello.wsgi

# Any directories that need to be added to the PYTHONPATH.
pythonpath: "{{ install_root }}/{{ project_name }}/hello/apps"

# the git repository URL for the project
project_repo: git@github.com:mtribaldos/django-hello-world.git
    
# a private key that has access to the repository URL
ssh_private_key: ~/.ssh/id_rsa

# The value of your django project's STATIC_ROOT settings.
# Here assumes that STATIC_ROOT is set in your settings.py like so:
# STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'static'))
static_root: "{{ install_root }}/{{ project_name }}/static"

# the dns name or names (space separated) for your server
server_name: django-hello.com www.django-hello.com

# database setup. Note that because this playbook doesn't touch the default 
# postgres pg_hba.conf file, we use local password-based authentication for
# postgres and thus you need to provide a username and password, and your
# settings.py MUST set "localhost" or "127.0.0.1" as the HOST value. For
# example, the default settings here assume the following values in
# settings.py:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'HOST': 'localhost',
#         'NAME': 'hello',
#         'USER': 'hello',
#         'PASSWORD': 'changeme',
#     }
# }
db_name: hello
db_user: hello
db_password: changeme

# apt packages, you should not need to change this unless you have packages
# listed in your requirements.txt that depend on system packages.
system_packages:
  - git
  - nginx
  - gunicorn
  - postgresql
  - postgresql-server-dev-all
  - python-pip
  - python-dev
  - python-psycopg2

# vim:ft=ansible:
